/** TENMON_BUILD_GREEN_RESTORE_AFTER_SHELTER_V1: 欠落復元用の最小定数（本カードは build green のみ） */
export const STRUCTURAL_COMPATIBILITY_AND_ROOT_SEPARATION_CARD_V1 =
  "STRUCTURAL_COMPATIBILITY_AND_ROOT_SEPARATION_V1" as const;
