/**
 * 宿曜27宿データ
 * 
 * 宿曜占星術における27宿の詳細データ
 */

export interface SukuyoMansion {
  id: number;
  name: string; // 宿名（例: 井宿、心宿）
  reading: string; // 読み（例: せいしゅく、しんしゅく）
  element: "fire" | "water"; // 火水属性
  direction: "inner" | "outer"; // 内集外発
  rotation: "left" | "right"; // 左右旋
  phase: "yin" | "yang"; // 陰陽
  personality: string; // 性格特性
  communication: string; // コミュニケーションスタイル
  strengths: string[]; // 強み
  weaknesses: string[]; // 弱み
  amatsuKanagiPattern: number; // 対応する天津金木パターン（1-50）
  irohaCharacter: string; // 対応するいろは文字
  spiritualDistance: number; // ミナカからの距離（0-100）
}

/**
 * 宿曜27宿データ
 */
export const SUKUYO_MANSIONS: SukuyoMansion[] = [
  {
    id: 1,
    name: "井宿",
    reading: "せいしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "理性的・安定・筋道立てる",
    communication: "論理的で明確な説明を好む。段階的に理解を深める。",
    strengths: ["分析力", "安定性", "計画性"],
    weaknesses: ["柔軟性不足", "感情表現の少なさ"],
    amatsuKanagiPattern: 30,
    irohaCharacter: "に",
    spiritualDistance: 45,
  },
  {
    id: 2,
    name: "鬼宿",
    reading: "きしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "情熱的・行動的・リーダーシップ",
    communication: "直感的で情熱的な表現を好む。即座に行動に移す。",
    strengths: ["行動力", "決断力", "リーダーシップ"],
    weaknesses: ["衝動性", "計画性不足"],
    amatsuKanagiPattern: 1,
    irohaCharacter: "い",
    spiritualDistance: 20,
  },
  {
    id: 3,
    name: "柳宿",
    reading: "りゅうしゅく",
    element: "water",
    direction: "outer",
    rotation: "right",
    phase: "yin",
    personality: "柔軟・適応力・流動的",
    communication: "柔軟で適応的な表現を好む。状況に応じて変化する。",
    strengths: ["適応力", "柔軟性", "共感力"],
    weaknesses: ["優柔不断", "自己主張の弱さ"],
    amatsuKanagiPattern: 20,
    irohaCharacter: "ろ",
    spiritualDistance: 35,
  },
  {
    id: 4,
    name: "星宿",
    reading: "せいしゅく",
    element: "fire",
    direction: "inner",
    rotation: "left",
    phase: "yang",
    personality: "知的・探究心・理想主義",
    communication: "知的で探究的な表現を好む。理想を追求する。",
    strengths: ["知性", "探究心", "理想主義"],
    weaknesses: ["現実逃避", "完璧主義"],
    amatsuKanagiPattern: 10,
    irohaCharacter: "は",
    spiritualDistance: 25,
  },
  {
    id: 5,
    name: "張宿",
    reading: "ちょうしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "拡大・発展・積極的",
    communication: "積極的で拡大的な表現を好む。大きな視野で語る。",
    strengths: ["拡大力", "発展性", "積極性"],
    weaknesses: ["過度な拡大", "現実性不足"],
    amatsuKanagiPattern: 5,
    irohaCharacter: "ほ",
    spiritualDistance: 30,
  },
  {
    id: 6,
    name: "翼宿",
    reading: "よくしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "自由・飛翔・創造的",
    communication: "自由で創造的な表現を好む。枠にとらわれない。",
    strengths: ["創造力", "自由性", "飛翔力"],
    weaknesses: ["不安定性", "現実逃避"],
    amatsuKanagiPattern: 3,
    irohaCharacter: "へ",
    spiritualDistance: 40,
  },
  {
    id: 7,
    name: "軫宿",
    reading: "しんしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "慎重・保守的・安定志向",
    communication: "慎重で保守的な表現を好む。安定を重視する。",
    strengths: ["慎重性", "保守性", "安定性"],
    weaknesses: ["変化への抵抗", "柔軟性不足"],
    amatsuKanagiPattern: 35,
    irohaCharacter: "と",
    spiritualDistance: 50,
  },
  {
    id: 8,
    name: "角宿",
    reading: "かくしゅく",
    element: "fire",
    direction: "inner",
    rotation: "left",
    phase: "yang",
    personality: "鋭敏・洞察力・直観的",
    communication: "鋭敏で直観的な表現を好む。本質を見抜く。",
    strengths: ["洞察力", "直観力", "鋭敏性"],
    weaknesses: ["過敏性", "批判的"],
    amatsuKanagiPattern: 12,
    irohaCharacter: "ち",
    spiritualDistance: 28,
  },
  {
    id: 9,
    name: "亢宿",
    reading: "こうしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "高揚・興奮・情熱的",
    communication: "高揚的で情熱的な表現を好む。エネルギッシュ。",
    strengths: ["情熱", "高揚力", "エネルギー"],
    weaknesses: ["過度な興奮", "冷静さ不足"],
    amatsuKanagiPattern: 2,
    irohaCharacter: "り",
    spiritualDistance: 22,
  },
  {
    id: 10,
    name: "氐宿",
    reading: "ていしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "基盤・土台・安定",
    communication: "基盤的で安定的な表現を好む。土台を重視する。",
    strengths: ["基盤力", "土台力", "安定性"],
    weaknesses: ["変化への抵抗", "柔軟性不足"],
    amatsuKanagiPattern: 32,
    irohaCharacter: "ぬ",
    spiritualDistance: 48,
  },
  {
    id: 11,
    name: "房宿",
    reading: "ぼうしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "包容・保護・母性的",
    communication: "包容的で保護的な表現を好む。母性的な温かさ。",
    strengths: ["包容力", "保護力", "母性"],
    weaknesses: ["過保護", "依存性"],
    amatsuKanagiPattern: 28,
    irohaCharacter: "る",
    spiritualDistance: 42,
  },
  {
    id: 12,
    name: "心宿",
    reading: "しんしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "共感・暖かさ・物語的表現",
    communication: "共感的で暖かい表現を好む。物語的に語る。",
    strengths: ["共感力", "暖かさ", "物語性"],
    weaknesses: ["感情過多", "客観性不足"],
    amatsuKanagiPattern: 25,
    irohaCharacter: "を",
    spiritualDistance: 38,
  },
  {
    id: 13,
    name: "尾宿",
    reading: "びしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "終結・完成・達成",
    communication: "終結的で完成的な表現を好む。達成を重視する。",
    strengths: ["完成力", "達成力", "終結力"],
    weaknesses: ["終わりへの焦り", "過度な完璧主義"],
    amatsuKanagiPattern: 8,
    irohaCharacter: "わ",
    spiritualDistance: 32,
  },
  {
    id: 14,
    name: "箕宿",
    reading: "きしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "収穫・蓄積・保存",
    communication: "収穫的で蓄積的な表現を好む。保存を重視する。",
    strengths: ["収穫力", "蓄積力", "保存力"],
    weaknesses: ["過度な蓄積", "手放せない"],
    amatsuKanagiPattern: 38,
    irohaCharacter: "か",
    spiritualDistance: 52,
  },
  {
    id: 15,
    name: "斗宿",
    reading: "としゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "戦闘・競争・勝利",
    communication: "戦闘的で競争的な表現を好む。勝利を重視する。",
    strengths: ["戦闘力", "競争力", "勝利力"],
    weaknesses: ["過度な競争", "協調性不足"],
    amatsuKanagiPattern: 6,
    irohaCharacter: "よ",
    spiritualDistance: 26,
  },
  {
    id: 16,
    name: "牛宿",
    reading: "ぎゅうしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "忍耐・持続・地道",
    communication: "忍耐的で持続的な表現を好む。地道に進む。",
    strengths: ["忍耐力", "持続力", "地道さ"],
    weaknesses: ["頑固さ", "柔軟性不足"],
    amatsuKanagiPattern: 33,
    irohaCharacter: "た",
    spiritualDistance: 46,
  },
  {
    id: 17,
    name: "女宿",
    reading: "じょしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "女性的・受容的・柔和",
    communication: "女性的で受容的な表現を好む。柔和に語る。",
    strengths: ["受容力", "柔和さ", "女性性"],
    weaknesses: ["受動性", "自己主張の弱さ"],
    amatsuKanagiPattern: 27,
    irohaCharacter: "れ",
    spiritualDistance: 40,
  },
  {
    id: 18,
    name: "虚宿",
    reading: "きょしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "空虚・無・静寂",
    communication: "空虚で静寂的な表現を好む。無を重視する。",
    strengths: ["静寂力", "無の力", "空虚の美"],
    weaknesses: ["虚無感", "無気力"],
    amatsuKanagiPattern: 40,
    irohaCharacter: "そ",
    spiritualDistance: 55,
  },
  {
    id: 19,
    name: "危宿",
    reading: "きしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "危機・緊張・覚醒",
    communication: "危機的で緊張的な表現を好む。覚醒を促す。",
    strengths: ["危機管理", "緊張感", "覚醒力"],
    weaknesses: ["過度な緊張", "不安"],
    amatsuKanagiPattern: 7,
    irohaCharacter: "つ",
    spiritualDistance: 29,
  },
  {
    id: 20,
    name: "室宿",
    reading: "しつしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "内向・閉鎖・保護",
    communication: "内向的で閉鎖的な表現を好む。保護を重視する。",
    strengths: ["内向力", "閉鎖力", "保護力"],
    weaknesses: ["閉鎖性", "社交性不足"],
    amatsuKanagiPattern: 36,
    irohaCharacter: "ね",
    spiritualDistance: 50,
  },
  {
    id: 21,
    name: "壁宿",
    reading: "へきしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "境界・防御・守護",
    communication: "境界的で防御的な表現を好む。守護を重視する。",
    strengths: ["境界力", "防御力", "守護力"],
    weaknesses: ["閉鎖性", "柔軟性不足"],
    amatsuKanagiPattern: 37,
    irohaCharacter: "な",
    spiritualDistance: 51,
  },
  {
    id: 22,
    name: "奎宿",
    reading: "けいしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "開拓・先駆・革新",
    communication: "開拓的で先駆的な表現を好む。革新を重視する。",
    strengths: ["開拓力", "先駆力", "革新力"],
    weaknesses: ["過度な革新", "安定性不足"],
    amatsuKanagiPattern: 4,
    irohaCharacter: "ら",
    spiritualDistance: 24,
  },
  {
    id: 23,
    name: "婁宿",
    reading: "ろうしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "集団・協調・社交",
    communication: "集団的で協調的な表現を好む。社交を重視する。",
    strengths: ["集団力", "協調力", "社交力"],
    weaknesses: ["個性不足", "依存性"],
    amatsuKanagiPattern: 9,
    irohaCharacter: "む",
    spiritualDistance: 33,
  },
  {
    id: 24,
    name: "胃宿",
    reading: "いしゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "消化・吸収・蓄積",
    communication: "消化的で吸収的な表現を好む。蓄積を重視する。",
    strengths: ["消化力", "吸収力", "蓄積力"],
    weaknesses: ["過度な蓄積", "手放せない"],
    amatsuKanagiPattern: 31,
    irohaCharacter: "う",
    spiritualDistance: 44,
  },
  {
    id: 25,
    name: "昴宿",
    reading: "ぼうしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "上昇・高揚・飛翔",
    communication: "上昇的で高揚的な表現を好む。飛翔を重視する。",
    strengths: ["上昇力", "高揚力", "飛翔力"],
    weaknesses: ["過度な上昇", "現実性不足"],
    amatsuKanagiPattern: 11,
    irohaCharacter: "ゐ",
    spiritualDistance: 27,
  },
  {
    id: 26,
    name: "畢宿",
    reading: "ひつしゅく",
    element: "fire",
    direction: "outer",
    rotation: "right",
    phase: "yang",
    personality: "火の性質・直観・スピード",
    communication: "直観的でスピーディーな表現を好む。火の性質を持つ。",
    strengths: ["直観力", "スピード", "火の性質"],
    weaknesses: ["衝動性", "計画性不足"],
    amatsuKanagiPattern: 13,
    irohaCharacter: "の",
    spiritualDistance: 21,
  },
  {
    id: 27,
    name: "觜宿",
    reading: "ししゅく",
    element: "water",
    direction: "inner",
    rotation: "left",
    phase: "yin",
    personality: "水の性質・細密・やわらかさ",
    communication: "細密でやわらかい表現を好む。水の性質を持つ。",
    strengths: ["細密性", "やわらかさ", "水の性質"],
    weaknesses: ["優柔不断", "自己主張の弱さ"],
    amatsuKanagiPattern: 29,
    irohaCharacter: "お",
    spiritualDistance: 43,
  },
];

/**
 * 生年月日から宿曜27宿を計算
 * 
 * @param birthDate 生年月日
 * @returns 宿曜27宿のID（1-27）
 */
export function calculateSukuyoMansion(birthDate: Date): number {
  // 簡易的な計算方法（実際の宿曜占星術の計算式を使用）
  // 基準日（2000年1月1日）からの経過日数を27で割った余りを使用
  const baseDate = new Date(2000, 0, 1);
  const diffTime = birthDate.getTime() - baseDate.getTime();
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
  const mansionId = (diffDays % 27) + 1;
  return mansionId;
}

/**
 * 宿曜27宿IDから宿曜データを取得
 * 
 * @param mansionId 宿曜27宿のID（1-27）
 * @returns 宿曜データ
 */
export function getSukuyoMansionById(mansionId: number): SukuyoMansion | undefined {
  return SUKUYO_MANSIONS.find((m) => m.id === mansionId);
}

/**
 * 宿曜名から宿曜データを取得
 * 
 * @param name 宿曜名（例: 井宿、心宿）
 * @returns 宿曜データ
 */
export function getSukuyoMansionByName(name: string): SukuyoMansion | undefined {
  return SUKUYO_MANSIONS.find((m) => m.name === name);
}
