#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
feature_autobuild_plan.json — intent → spec → カード分割 → 実行順（自動実行はしない）
PARENT_06: high risk カードはプラン上も after_manual_approval のみ。
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, List

VERSION = 1
CARD = "TENMON_SELF_BUILD_OS_PARENT_06_FEATURE_AUTOBUILD_ORCHESTRATOR_CURSOR_AUTO_V1"
VPS_MARKER = "TENMON_SELF_BUILD_OS_PARENT_06_FEATURE_AUTOBUILD_AND_REMOTE_ADMIN_VPS_V1"


def api_automation() -> Path:
    return Path(__file__).resolve().parent


def utc_now_iso() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _read(p: Path) -> Dict[str, Any]:
    if not p.is_file():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return {}


def _keywords(intent: str) -> List[str]:
    words = re.findall(r"[a-zA-Z0-9_ぁ-んァ-ン一-龯]{2,}", intent)
    seen: List[str] = []
    for w in words:
        if w.lower() in ("the", "and", "for", "api", "tenmon") or w in seen:
            continue
        seen.append(w)
        if len(seen) >= 12:
            break
    return seen


def _infer_cards(intent: str, constraints: List[str]) -> List[Dict[str, Any]]:
    """決定論的ヒューリスティック（LLM 不使用）。"""
    low = intent.lower()
    cards: List[Dict[str, Any]] = []
    order = 1

    def add(cid: str, name: str, risk: str, note: str) -> None:
        nonlocal order
        cards.append(
            {
                "order": order,
                "logical_id": cid,
                "card_name": name,
                "risk_tier": risk,
                "execute_mode": "after_manual_approval" if risk == "high" else "after_approval_gate",
                "one_line_objective": note,
            }
        )
        order += 1

    if any(x in low for x in ("route", "ルート", "endpoint", "api")):
        add("observe_routes", "TENMON_OBSERVATION_OS_CURSOR_AUTO_V1", "medium", "route / 契約の観測のみ")
    if any(x in low for x in ("automation", "自動", "script", "python")):
        add("automation", "TENMON_FEATURE_AUTOBUILD_OS_CURSOR_AUTO_V1", "medium", "automation 配下の安全な追加")
    if any(x in low for x in ("ui", "ダッシュボード", "dashboard", "管理")):
        add("admin_ui", "TENMON_REMOTE_CURSOR_COMMAND_CENTER_CURSOR_AUTO_V1", "low", "管理者経路・投入 UI")
    if any(x in low for x in ("learning", "学習", "seed", "kg")):
        add("learning", "TENMON_LEARNING_INTEGRATION_OS_CURSOR_AUTO_V1", "high", "学習系は high: 自動実行禁止")
    if any(x in low for x in ("chat", "会話", "応答")) and "契約" not in low:
        add("chat_surface", "CHAT_TS_STAGE1_SURFACE_POLISH_CURSOR_AUTO_V1", "high", "chat 近傍は high（本文禁止遵守）")
    if not cards:
        add("generic", "TENMON_SELF_BUILD_OS_PARENT_06_FEATURE_AUTOBUILD_AND_REMOTE_ADMIN_CURSOR_AUTO_V1", "medium", "汎用 feature カード")

    if constraints:
        cards.append(
            {
                "order": order,
                "logical_id": "constraints_echo",
                "card_name": "TENMON_FEATURE_SPEC_CONSTRAINTS_CURSOR_AUTO_V1",
                "risk_tier": "low",
                "execute_mode": "after_approval_gate",
                "one_line_objective": "constraints: " + "; ".join(constraints[:8]),
            }
        )
    return cards


def build_from_intent(intent: str, constraints: List[str], suggested_name: str | None) -> Dict[str, Any]:
    kw = _keywords(intent)
    parsed = {
        "theme_keywords": kw,
        "constraints": constraints,
        "suggested_card_name": suggested_name or "TENMON_FEATURE_SPEC_INTENT_CURSOR_AUTO_V1",
    }
    spec_md = "\n".join(
        [
            "## Feature spec (autogenerated)",
            "",
            "### Intent",
            intent[:8000],
            "",
            "### Parsed keywords",
            ", ".join(kw) if kw else "(none)",
            "",
            "### Policy",
            "- 高リスクカードはオーケストレータが自動実行しない",
            "- 承認ゲート通過後に Cursor カードとして投入",
        ]
    )
    cursor_cards = _infer_cards(intent, constraints)
    execution_order = [c["order"] for c in cursor_cards]
    return {
        "version": VERSION,
        "card": CARD,
        "generatedAt": utc_now_iso(),
        "intent_raw": intent[:12000],
        "parsed": parsed,
        "spec_md": spec_md,
        "cursor_cards": cursor_cards,
        "execution_order": execution_order,
        "high_risk_blocked_auto": True,
        "notes": [
            "実行は remote_admin_queue / remote_cursor_queue の承認フローへ",
            "chat.ts 本体・DB schema・dist・kokuzo_pages 正文はカード側 DO_NOT_TOUCH を遵守",
        ],
    }


def load_intake_from_queue(intake_id: str) -> tuple[str, List[str], str | None]:
    q = _read(api_automation() / "remote_admin_queue.json")
    for it in q.get("items") or []:
        if str(it.get("id")) != intake_id:
            continue
        payload = it.get("payload") or {}
        if str(payload.get("kind")) != "feature_spec_card":
            continue
        intent = str(payload.get("intent_text") or "").strip()
        cons = [str(x) for x in (payload.get("constraints") or []) if x is not None]
        sug = payload.get("suggested_card_name")
        return intent, cons, str(sug).strip() if sug else None
    return "", [], None


def main() -> int:
    ap = argparse.ArgumentParser(description="feature_autobuild_orchestrator_v1")
    ap.add_argument("--intake-id", type=str, default="", help="remote_admin_queue.json の item id")
    ap.add_argument("--intent-file", type=str, default="", help="意図テキストファイル")
    ap.add_argument("--out", type=str, default="")
    args = ap.parse_args()
    auto = api_automation()
    intent = ""
    constraints: List[str] = []
    suggested: str | None = None

    if args.intake_id:
        intent, constraints, suggested = load_intake_from_queue(args.intake_id.strip())
    if args.intent_file:
        p = Path(args.intent_file)
        if p.is_file():
            intent = p.read_text(encoding="utf-8", errors="replace").strip()
    if not intent:
        intent = "(empty intent — pass --intake-id or --intent-file)"

    body = build_from_intent(intent, constraints, suggested)
    body["source_intake_id"] = args.intake_id.strip() or None
    out = Path(args.out) if args.out else auto / "feature_autobuild_plan.json"
    out.write_text(json.dumps(body, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    (auto / VPS_MARKER).write_text(f"{VPS_MARKER}\n{utc_now_iso()}\n", encoding="utf-8")
    print(json.dumps({"ok": True, "path": str(out), "cards": len(body.get("cursor_cards") or [])}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
