#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TENMON_MAC_REDEPLOY_REALRUN_BRIDGE_CURSOR_AUTO_V1

Mac 再配備用の payload 指針と runbook 断片を repo 内に生成する（Mac 直操作は不要）。
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

CARD = "TENMON_MAC_REDEPLOY_REALRUN_BRIDGE_CURSOR_AUTO_V1"
OUT_JSON = "tenmon_mac_redeploy_realrun_bridge_summary.json"


def utc() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def main() -> int:
    repo = Path(os.environ.get("TENMON_REPO_ROOT", "/opt/tenmon-ark-repo")).resolve()
    api = repo / "api"
    auto = api / "automation"
    scripts = api / "scripts"
    out_dir = auto / "out" / "dialogue_no_midrun_mac_redeploy"
    out_dir.mkdir(parents=True, exist_ok=True)

    redeploy_sh = scripts / "tenmon_mac_runtime_redeploy_v1.sh"
    check_r: dict[str, Any] = {"ok": False, "exit_code": None, "stdout_tail": "", "stderr_tail": ""}
    if redeploy_sh.is_file():
        try:
            cp = subprocess.run(
                ["bash", str(redeploy_sh), "check"],
                cwd=str(api),
                capture_output=True,
                text=True,
                timeout=120,
                check=False,
                env={**os.environ, "TENMON_REPO_ROOT": str(repo)},
            )
            check_r = {
                "ok": cp.returncode == 0,
                "exit_code": cp.returncode,
                "stdout_tail": (cp.stdout or "")[-8000:],
                "stderr_tail": (cp.stderr or "")[-2000:],
            }
        except Exception as e:
            check_r["stderr_tail"] = str(e)[:400]

    payload_files = [
        str(scripts / "tenmon_cursor_watch_loop.sh"),
        str(auto / "tenmon_mac_executor_result_return_and_acceptance_bind_v1.py"),
        str(auto / "browser_ai_operator_v1.py"),
        str(auto / "cursor_review_acceptor_v1.py"),
    ]

    scp_lines = [
        "# generated by TENMON_MAC_REDEPLOY_REALRUN_BRIDGE — verify TENMON_MAC_VPS_* before use",
        "set -euo pipefail",
        'MAC_HOME="${TENMON_MAC_HOME:-$HOME/tenmon-mac}"',
        'mkdir -p "$MAC_HOME"',
        f'scp "$VPS:$R/api/scripts/tenmon_cursor_watch_loop.sh" "$MAC_HOME/"',
        f'scp "$VPS:$R/api/automation/tenmon_mac_executor_result_return_and_acceptance_bind_v1.py" "$MAC_HOME/"',
        f'scp "$VPS:$R/api/automation/browser_ai_operator_v1.py" "$MAC_HOME/"',
        f'scp "$VPS:$R/api/automation/cursor_review_acceptor_v1.py" "$MAC_HOME/"',
        'chmod +x "$MAC_HOME/tenmon_cursor_watch_loop.sh" 2>/dev/null || true',
    ]
    scp_path = out_dir / "scp_payload_suggest.sh"
    scp_path.write_text("\n".join(scp_lines) + "\n", encoding="utf-8")

    runbook_md = "\n".join(
        [
            f"# Mac redeploy / real-run bridge ({CARD})",
            "",
            f"- generated_at: `{utc()}`",
            "- SSOT: `api/docs/constitution/TENMON_MAC_RUNTIME_REDEPLOY_AND_RESTART_RUNBOOK_CURSOR_AUTO_V1.md`",
            "- watch loop real-run 条件: `TENMON_MAC_WATCH_LOOP_REAL_EXECUTION_ENABLE_FOR_APPROVED_HIGH_RISK_CURSOR_AUTO_V1.md`",
            "",
            "## Payload paths (repo)",
            "",
            *[f"- `{p}`" for p in payload_files],
            "",
            "## Suggested scp script",
            "",
            f"- `{scp_path}`",
            "",
            "## Local check (VPS)",
            "",
            f"- `bash api/scripts/tenmon_mac_runtime_redeploy_v1.sh check`",
            "",
        ]
    )
    rb_path = out_dir / "mac_redeploy_realrun_runbook_fragment.md"
    rb_path.write_text(runbook_md + "\n", encoding="utf-8")

    summary = {
        "card": CARD,
        "generated_at": utc(),
        "ok": True,
        "redeploy_script_check": check_r,
        "out_dir": str(out_dir),
        "payload_relative_paths": [str(Path(p).relative_to(repo)) for p in payload_files if Path(p).is_file()],
        "scp_suggest_script": str(scp_path),
        "runbook_fragment": str(rb_path),
        "next_on_pass": "TENMON_DIALOGUE_POST_REDEPLOY_REALRUN_RECHECK_CURSOR_AUTO_V1",
        "next_on_fail_note": "停止。retry 1枚のみ生成。",
    }
    (auto / OUT_JSON).write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"ok": True, "path": str(auto / OUT_JSON)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
